server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XYpJy5Xg0tjKeydqQAi2CdNZb94NBx0quKE5Aw2v/ntvG74zIw6c1ozd/f+rPKcPdFt6mlfcNS5aOySb2PJFJw==
    url:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20 # 数据库连接池的初始化大小
      min-idle: 20 # 数据库连接池中的最小空闲连接
      max-active: 50 # 数据库连接池的最大连接数
      max-wait: 60000 # 获取连接时最大等待时间
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${druid.decrypt.key}

# 密钥配置（建议从环境变量或安全配置中心获取）
druid:
  decrypt:
    key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANWnnwZyMySAmBbKOg/HGYIXRLZKuPi7BQXydB23w7dZhWv6XMjgAob/E/dlxdXwBHNs3zbILp3gglxFUBwA/mkCAwEAAQ==

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  config: classpath:log4j2-spring.xml

es:
  cluster:
    es-configs:
      - name:
        nodes:
